# Generated by Django 3.1.8 on 2024-11-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100, unique=True)),
                ('presentation', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['medication_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicationsku',
            constraint=models.UniqueConstraint(fields=('medication_name', 'presentation', 'dose', 'unit'), name='unique_medication_sku_combination'),
        ),
    ]
